config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations}
  authenticated :user do
    root 'books#index', as: :authenticated_root
  end

  resources :users, only: [:show]

  resources :books, only: %i[index show new create edit update]

  resources :conversations, only: %i[show create]

  root 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :cover
  has_many_attached :images
  has_many :conversations, dependent: :destroy

  validates :title, :description, :user, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create edit update]
  before_action :find_book, only: %i[show edit update]

  def index
    @books = Book.all
  end

  def show; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.save!
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :description, :cover, images: [])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @hide_nav = true
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_update_path_for(user)
    user_path(user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :avatar])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<section class='basic-form'>
  <%= form_with model: @book, local: true do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :author %>
    <%= f.text_field :author %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :cover %>
    <%= f.file_field :cover %>

    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>

    <%= f.submit 'Enviar' %>
  <% end %>

  <%= link_to 'Voltar', books_path %>
</section>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<section class='feed'>
  <%= render 'layouts/shared/user_info_menu' %>

  <section class='books-list'>
    <% @books.each do |book| %>
    <div class='card transparent'>
     <div class="card-image">
       <% if book.cover.attached? %>
         <%= image_tag(book.cover) %>
       <% end %>
     </div>
      <div class='card-content'>
        <span class='card-title'>
          <%= link_to truncate(book.title, length: 25), book_path(book) %>
        </span>
        <p><%= truncate(book.description, length: 25) %></p>
      </div>
    </div>
    <% end %>
  </section>

  <%= render 'layouts/shared/user_side_menu' %>
</section>

app/views/books/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<section class='feed'>
  <%= render 'layouts/shared/user_info_menu' %>

  <section class='book-info'>
    <% if @book.images.attached? %>
      <% @book.images.each do |image| %>
        <%= image_tag(image.variant(resize_to_fit: [200, 200])) %>
      <% end %>
    <% end %>
    <h1><%= @book.title %></h1>
    <h3><%= @book.author %></h3>
    <p><%= @book.description %></p>

    <%= link_to 'Voltar', books_path %>
  </section>

  <%= render 'layouts/shared/user_side_menu' %>
</section>

app/views/conversations/show.html.erb
<% @book.conversations.each do |conversation| %>
  <%= conversation.content %>
<% end %>

app/views/homepage/index.html.erb
<section class='homepage'>
  <div class='homepage-description'>
    <h1>Seboo Conecta pessoas que estejam doando seus livros com outras pessoas que estão procurando livros.</h1>
    <h2>Coloque seus livros a disposição de outras pessoas que estão procurando livros.</h2>
    <h2>Encontre livros que você tenha interesse.</h2>
    <div class='homepage-actions'>
      <%= link_to 'Cadastre-se', new_user_registration_path, class: 'waves-effect waves-light btn' %>
      <%= link_to 'Entrar', new_user_session_path, class: 'waves-effect waves-light btn' %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookTrade</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' unless @hide_nav %>

    <% flash.each do |name, msg| %>
      <p class="<%= name %>"><%= msg %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper purple">
    <%= link_to "Home", root_path, class: 'brand-logo' %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Adicionar Livro', new_book_path %></li>
      <% else %>
        <li><%= link_to 'Entrar', new_user_session_path %></li>
        <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
      

app/views/layouts/shared/_user_info_menu.erb
<section class='user-menu'>
  <% if current_user.avatar.attached? %>
    <%= image_tag(current_user.avatar.variant(resize_to_fit: [200, 150]), class: 'user-menu-image responsive-img') %>
  <% end %>
  <h3 class='user-menu-name'>Name</h3>
  <div class='user-menu-links'>
    <%= link_to 'Editar Perfil', edit_user_registration_path(current_user) %>
  </div>
  <%= link_to 'Perfil', user_path(current_user), class: 'user-menu-btn btn purple' %>
</section>

app/views/layouts/shared/_user_side_menu.erb
<section class='user-sidemenu'>
  <%# <%= link_to 'Conversations', conversation_path(@book) %>
  <h3 class='user-sidemenu-title'>Title</h3>
  <a class='user-sidemenu-link' href='#'>Link</a>
  <a class='user-sidemenu-link' href='#'>Link</a>
  <a class='user-sidemenu-link' href='#'>Link</a>
  <a class='user-sidemenu-link' href='#'>Link</a>
</section>

app/views/users/show.html.erb
<% if @user.avatar.attached? %>
  <%= image_tag @user.avatar %>
<% end %>
<%= @user.name %>
<%= @user.email %>